---
# tasks file for kube-node
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Fetching K8S-1.6 Main Package
  get_url:
    url: https://s3.amazonaws.com/k8s-dep-file/k8s-1.6-rpm/kubernetes-1.6.7-1.el7.x86_64.rpm
    dest: /root
    mode: 0644

- name: Fetching K8S-1.6 Master Package
  get_url:
    url: https://s3.amazonaws.com/k8s-dep-file/k8s-1.6-rpm/kubernetes-master-1.6.7-1.el7.x86_64.rpm
    dest: /root
    mode: 0644

- name: Fetching K8S-1.6 Node Package
  get_url:
    url: https://s3.amazonaws.com/k8s-dep-file/k8s-1.6-rpm/kubernetes-node-1.6.7-1.el7.x86_64.rpm
    dest: /root
    mode: 0644

- name: Fetching K8S-1.6 Client Package
  get_url:
    url: https://s3.amazonaws.com/k8s-dep-file/k8s-1.6-rpm/kubernetes-client-1.6.7-1.el7.x86_64.rpm
    dest: /root
    mode: 0644

- name: Install epel-release for centos7
  yum: name=epel-release state=present

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - flannel
    - /root/kubernetes-1.6.7-1.el7.x86_64.rpm
    - /root/kubernetes-master-1.6.7-1.el7.x86_64.rpm
    - /root/kubernetes-node-1.6.7-1.el7.x86_64.rpm
    - /root/kubernetes-client-1.6.7-1.el7.x86_64.rpm
    - curl
    - telnet
    - wget
    - ntp
    - openssl
    - bind-utils

- name: Flush IPtables
  command: iptables -F

- name: disable selinux
  command: setenforce 0

- name: Fetching Node's IP.
  shell: curl http://169.254.169.254/latest/meta-data/local-ipv4
  register: Node_IP

- debug: msg="{{Node_IP.stdout}}"


- name: Set Node IP
  set_fact:
    NODE: "{{ Node_IP.stdout }}"


- name: Configure etcd server for flannel service
  lineinfile:
    dest: /etc/sysconfig/flanneld
    regexp: '^FLANNEL_ETCD_ENDPOINTS='
    line: 'FLANNEL_ETCD_ENDPOINTS="http://{{ MASTERPRIVATEIP }}:2379"'
    owner: root
    group: root
    mode: 0644

- name: Configure etcd server for flannel prefix
  lineinfile:
    dest: /etc/sysconfig/flanneld
    regexp: '^FLANNEL_ETCD_PREFIX='
    line: 'FLANNEL_ETCD_PREFIX="/kube-centos/network"'
    owner: root
    group: root
    mode: 0644

- name: update KUBE_MASTER in kubernetes default config
  lineinfile:
    dest: /etc/kubernetes/config
    regexp: '^KUBE_MASTER='
    line: 'KUBE_MASTER="--master=http://{{ MASTERPRIVATEIP }}:8080"'
    owner: root
    group: root
    mode: 0644


- name: Adding ETCD config 
  lineinfile:
    path: /etc/kubernetes/config
    line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://{{ MASTERPRIVATEIP }}:2379"'
    owner: root
    group: root
    mode: 0644

- name: Configure kubelet service - KUBELET_ADDRESS
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_ADDRESS='
    line: 'KUBELET_ADDRESS="--address=0.0.0.0"'
    owner: root
    group: root
    mode: 0644
  
- name: Configure kubelet service - KUBELET_PORT
  lineinfile:
    path: /etc/kubernetes/kubelet
    line: 'KUBELET_PORT="--port=10250"'
    owner: root
    group: root
    mode: 0644

- name: Configure kubelet service - KUBELET_HOSTNAME
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_HOSTNAME='
    line: 'KUBELET_HOSTNAME="--hostname-override={{ NODE }}"'
    owner: root
    group: root
    mode: 0644
  
- name: Configure kubelet service - KUBELET_API_SERVER
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_API_SERVER='
    line: 'KUBELET_API_SERVER="--api-servers=http://{{ MASTERPRIVATEIP }}:8080"'
    owner: root
    group: root
    mode: 0644

- name: Configure kubelet service - KUBELET_HOSTNAME
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: '^KUBELET_ARGS='
    line: 'KUBELET_ARGS="--cgroup-driver=systemd --cluster-dns=10.254.3.100 --cluster-domain=cluster.local --cloud-provider=aws"'
    owner: root
    group: root
    mode: 0644

- name: Restart NODE services
  command: systemctl restart {{ item }}
  with_items:
    - kube-proxy
    - kubelet
    - docker
    - flanneld

- name: Enable NODE services to restart on boot
  command: systemctl enable {{ item }}
  with_items:
    - kube-proxy
    - kubelet
    - docker
    - flanneld
